#!/bin/sh
echo '[git hook] executing spotlessApply to format code before commit'

# Stash any unstaged changes
git stash -q --keep-index

# Run spotlessApply
# We pass in ratchetFrom here to ensure that we only format the files that have changed since the last commit
if command -v gradle > /dev/null 2>&1 # Check if gradle command exists to support GitHub Desktop on Windows
then
  gradle spotlessApply -PratchetFrom=HEAD # Requires Gradle to be installed
else
  ./gradlew spotlessApply -PratchetFrom=HEAD # Otherwise call gradle wrapper for Mac-OS / Unix / Git for Windows
fi

# Store the last exit code in a variable
RESULT=$?

# Stage formatting changes
git add -u

# Un-stash the stashed changes
git stash pop -q

# Return the 'spotlessApply' exit code
exit $RESULT